'use strict';

const mongoose = require('mongoose');

exports.getNewProjectTemplate = function(projectCode) {
	var fields = {
        'lastEditor' : ('54b598906fac250a6ba470d7'),
        'user' : ('54d11aeeef27b57820ddffec'),
        'customer' : ('550b2e54e94268002368b81b'),
        'organism' : ('5588149422f8439c533770f4'),
        'analysisStageComment' : '',
        'analysisStage' : 'N/A',
        'bedFileComment' : '',
        'bedFile' : 'N/A',
        'referenceGenomeFileComment' : '',
        'referenceGenomeFile' : 'N/A',
        'probeFileComment' : '',
        'probeFile' : 'N/A',
        'contractComment' : '',
        'contract' : 'N/A',
        'totalReagentsAndLibraryComment' : '',
        'totalReagentsAndLibrary' : '$123.00',
        'totalProbesComment' : '',
        'totalProbes' : '$123.00',
        'totalSequencingComment' : '',
        'totalSequencing' : '$123',
        'invoicesComment' : '',
        'invoices' : 'N/A',
        'totalContractComment' : '',
        'totalContract' : '$123.00',
        'priceComment' : '',
        'price' : '$123.00',
        'arrivalImageNames' : [],
        'arrivalImages' : [],
        'gelImageNames' : [
            'AMN_666901_QC_Gel_gDNA.JPG'
        ],
        'gelImages' : [
            '569e564b72b72fd07af79360'
        ],
        'machineTypeComment' : '',
        'machineType' : 'HiSeq3000 V1',
        'indexingModeComment' : '',
        'indexingMode' : 'Dual',
        'enzymeComment' : '',
        'enzyme' : 'Kapa',
        'sequencingTypeComment' : '',
        'sequencingType' : 'PairedEnd',
        'daysSinceSamplesOrderedComment' : '',
        'samplesOrderedDateComment' : '',
        'samplesOrderedDate' : null,
        'samplesArrivalDateComment' : '',
        'samplesArrivalDate' : new Date(),
        'arrivedSamplesComment' : '',
        'totalSamplesExpectedComment' : '',
        'totalSamplesExpected' : '192',
        'probesOrderedDateComment' : '',
        'probesOrderedDate' : null,
        'numberOfProbesComment' : '',
        'probeProviderComment' : '',
        'probeComment' : '',
        'probe' : 'UCE-5Kv1',
        'lastLaneUsageComment' : '',
        'lastLaneUsage' : 1,
        'sequencingPlexComment' : '',
        'sequencingPlex' : '192',
        'capturePlexComment' : '',
        'capturePlex' : '24',
        'logs' : [
            ('569d638990100487752e1070')
        ],
        'userComment' : '',
        'projectStatusComment' : '',
        'projectStatus' : false,
        'description' : '',
        'platesComment' : '',
        'plates' : [
            ('569e526290100487752e107f'),
            ('569e526290100487752e1080')
        ],
        'sequencingMethodComment' : '',
        'sequencingMethod' : 'Capture-Seq',
        'organismComment' : '',
        'customerComment' : '',
        'projectCodeComment' : '',
        'projectCode' : projectCode,
        'lastEditedComment' : '',
        'lastEdited' : new Date(),
        'daysSinceCreationComment' : '',
        'daysUntilDueComment' : '',
        'dueComment' : '',
        'due' : new Date(),
        'mismatchPercentageComment' : '',
        'mismatchPercentage' : '',
        'projectCreatedDateComment' : '',
        'created' : new Date(),
        '__v' : 4,
        'daysUntilProbeArrivalComment' : '',
        'isUrgent' : false,
        'shearingMethod' : 'Seq2',
        'shearingMethodComment' : ''
    };
		return fields;
};
